# Generated by Django 5.2.17 on 2026-09-04 16:11

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_doc', '0042_project_index_position'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIProvider',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider', models.CharField(max_length=50)),
                ('api_key', models.CharField(max_length=200)),
                ('base_url', models.URLField(blank=True, null=True)),
                ('model_type', models.CharField(default='text_generate', max_length=100, verbose_name='模型类型')),
                ('model_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='模型名称')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': 'AI 模型提供商',
                'verbose_name_plural': 'AI 模型提供商',
            },
        ),
        migrations.CreateModel(
            name='Prompt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Prompt 名称')),
                ('desc', models.TextField(blank=True, default='', verbose_name='Prompt 描述')),
                ('value', models.TextField(verbose_name='Prompt 内容')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('modify_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
            ],
            options={
                'verbose_name': 'Prompt',
                'verbose_name_plural': 'Prompt 管理',
            },
        ),
        migrations.CreateModel(
            name='DocAISection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_title', models.CharField(max_length=255)),
                ('section_title', models.CharField(default='', max_length=1024)),
                ('title_path', models.CharField(default='', max_length=1024)),
                ('content', models.TextField()),
                ('embedding_text', models.TextField(blank=True)),
                ('embedding', models.JSONField(blank=True, null=True)),
                ('embedding_status', models.CharField(default='pending', max_length=20)),
                ('summary', models.TextField(blank=True)),
                ('keywords', models.JSONField(default=list)),
                ('tags', models.JSONField(default=list)),
                ('faqs', models.JSONField(default=list)),
                ('llm_status', models.CharField(default='pending', max_length=20)),
                ('order', models.IntegerField(default=0)),
                ('source_type', models.CharField(default='raw', max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('doc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_sections', to='app_doc.doc')),
            ],
            options={
                'verbose_name': '文档AI切片',
                'verbose_name_plural': '文档AI切片',
            },
        ),
    ]
